# Generated by Django 4.0.3 on 2022-04-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_answer_slug_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questions',
        ),
    ]
