# Generated by Django 4.0.3 on 2022-04-06 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_question_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorite_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
